name: BlueGreen Deployment

on:
    workflow_run:
        workflows: ["CD"]
        types:
            - completed
permissions:
    contents: read

jobs:
    deployandstart:
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        runs-on: ubuntu-latest

        steps:
            - name: configure ec2 authentication
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    whoami
                    hostname

                    # Login to ECR from EC2
                    aws ecr get-login-password --region us-east-1 | \
                    docker login --username AWS --password-stdin \
                    283609055440.dkr.ecr.us-east-1.amazonaws.com

                    #pulling the docker image

                    docker pull 283609055440.dkr.ecr.us-east-1.amazonaws.com/springboot-cicd:${{ github.event.workflow_run.head_sha }}
                    docker images

            - name: Capture old image 
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    if docker ps -a -q --filter "name=^springboot-app$" | grep -q .; then

                        echo "Existing springboot-app container found."

                        OLD_IMAGE=$(docker inspect --format='{{.Config.Image}}' springboot-app)

                        echo "Old image: $OLD_IMAGE"

                        echo "$OLD_IMAGE" > /home/ubuntu/old_image.txt

                        # if docker ps -q --filter "name=^springboot-app$" | grep -q .; then
                        # echo "Stopping the existing container..."
                        # docker stop springboot-app
                        # fi

                        # echo "Removing the existing container..."
                        # docker rm springboot-app

                    else

                        echo "No existing springboot-app container found."
                        rm -f /home/ubuntu/old_image.txt

                    fi


            - name: start the container 
              id: deploy_new
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    echo "Starting new Spring Boot container..."

                    docker run -d --name springboot-app-new -p 8081:8080 283609055440.dkr.ecr.us-east-1.amazonaws.com/springboot-cicd:${{ github.event.workflow_run.head_sha }} || exit 1

                    echo "New Container is started..."
                    sleep 20
                    if curl --fail http://localhost:8081; then
                        echo " application running successfully with new name"
                    else
                        echo " Application is not Running"
                        exit 1
                    fi
            - name:  switch traffic 
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  echo "switching traffic to the green environment "
                  sudo sed -i 's|proxy_pass http://127.0.0.1:8080;|proxy_pass http://127.0.0.1:8081;|' /etc/nginx/sites-available/default
                  echo "Testing the nginx configuration"
                  sudo nginx -t
                  echo " nginx is reloading "
                  sudo systemctl reload nginx 

                  echo "traffic is switched to green successfully .. "
            - name: stop the blue container
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  if curl --fail http://localhost:8081; then
                    echo " the greeen deploy is success and traffic is switched"
                    echo " stopping the blue container"
                    docker stop springboot-app
                    
                    echo " removing blue container"
                    docker rm springboot-app
                  else
                    echo " Traffic not able to communicate green.."
                    exit 1
                  fi

            # - name: Roll Back to the old image
            #   if: ${{ failure() && steps.deploy_new.outcome == 'failure' }}
            #   uses: appleboy/ssh-action@v1
            #   with:
            #     host: ${{ secrets.EC2_HOST }}
            #     username: ${{ secrets.EC2_USER }}
            #     key: ${{ secrets.EC2_SSH_KEY }}
            #     script: |
            #       echo "Roll Back step started"
            #       if [ -f /home/ubuntu/old_image.txt ]; then
            #         echo "Application is not runnig"
            #         docker stop springboot-app
            #         docker rm springboot-app
            #         OLD_IMAGE=$(cat /home/ubuntu/old_image.txt)
            #         echo "Old Image is : ${OLD_IMAGE}"
            #         docker run -d --name springboot-app -p 8080:8080 ${OLD_IMAGE}
            #         sleep 20
            #         if curl --fail http://localhost:8080; then
            #           echo "Application is runnig successfully...."
            #         else
            #           echo "Application not working on ROLLBACK......"
            #         fi
            #       else
            #         echo " the old image file not found "
            #         echo " Not possible for the Roll Back"
            #         exit 1
            #       fi

              
