name: CD

on:
    workflow_run:
        workflows: ["CI"]
        types:
            - completed

permissions:
    id-token: write
    contents: read

jobs:

    Deployemt:
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        runs-on: ubuntu-latest
        steps:
            - name: CD Started
              run: echo "CI succeded and CD started"
            - name: Debug OIDC claims
              env:
                ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
                ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
              run: |
                TOKEN=$(curl -sSf \
                    -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                    "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
                    | jq -r '.value')

                echo "$TOKEN" \
                    | cut -d '.' -f2 \
                    | base64 -d 2>/dev/null \
                    | jq '{sub, aud, repository, ref, job_workflow_ref}'
            - name: Show OIDC subject
              run: |
                echo "Repository: ${{ github.repository }}"
                echo "Event: ${{ github.event_name }}"
                echo "Workflow: ${{ github.event.workflow_run.name }}"
            - name: Configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::283609055440:role/GitHubActions-SpringBoot-Testing
                aws-region: us-east-1

            - name: verify aws credentias
              run: aws sts get-caller-identity
              
