name: CD

on:
    workflow_run:
        workflows: ["CI"]
        types:
            - completed

permissions:
    contents: read

jobs:

    Deployemt:
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        runs-on: ubuntu-latest
        steps:
            - name: CD Started
              run: echo "CI succeded and CD started"